# Generated by Django 2.2 on 2020-04-27 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarinscription',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='seminarinscription',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
