# Generated by Django 2.2 on 2019-08-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='instructor',
            new_name='instructors',
        ),
        migrations.AddField(
            model_name='seminar',
            name='inscription_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
