# Generated by Django 2.2 on 2020-04-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0002_auto_20200427_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='inscription_link',
            field=models.TextField(blank=True),
        ),
    ]
